#FROM ubuntu:disco
FROM arm32v7/debian:unstable

ENV DEBIAN_FRONTEND noninteractive
ENV LC_ALL C.UTF-8

# Update packages and install dependencies
RUN apt-get update && apt-get -y upgrade && apt-get -y clean
RUN apt-get install -y protobuf-compiler libh2o-dev libcurl4-openssl-dev \
        libssl-dev libprotobuf-dev libh2o-evloop-dev libwslay-dev libeigen3-dev libzstd-dev \
	make clang-9 git build-essential curl autoconf automake libfmt-dev libncurses5-dev \
    && apt-get -y clean

# Build
ADD . /galmon/
WORKDIR /galmon/
RUN make 
ENV PATH=/galmon:${PATH}
